# Generated by Django 4.2 on 2023-05-05 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='author_badge',
            field=models.CharField(default='Novice', max_length=255),
        ),
        migrations.AddField(
            model_name='comment',
            name='author_badge',
            field=models.CharField(default='Novice', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='author_badge',
            field=models.CharField(default='Novice', max_length=255),
        ),
    ]
