# Generated by Django 4.2 on 2023-05-11 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_answer_author_badge_comment_author_badge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.PositiveIntegerField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_image', models.URLField()),
                ('author_badge', models.CharField(default='Novice', max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('views_number', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(to='app.tag')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author_id', models.PositiveIntegerField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_badge', models.CharField(default='Novice', max_length=255)),
                ('author_image', models.URLField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.article')),
            ],
        ),
    ]
