# Generated by Django 4.2 on 2023-06-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_article_articlecomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='author_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
